# Generated by Django 4.1.7 on 2023-03-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_recipes_created',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
