# Generated by Django 4.1.7 on 2023-03-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_number_of_recipes_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number_of_recipes_created',
        ),
    ]
