# Generated by Django 4.1.7 on 2023-03-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_number_of_recipes_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_recipes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
