# Generated by Django 4.1.7 on 2023-03-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_num_recipes_userprofile_recipes_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='recipes_created',
        ),
    ]
