# Generated by Django 4.1.7 on 2023-04-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_recipes_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='John Smith', max_length=100),
            preserve_default=False,
        ),
    ]
