# Generated by Django 4.1.7 on 2023-03-08 04:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='userID',
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
