# Generated by Django 4.1.7 on 2023-03-10 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0007_alter_shoppinglistitem_recipeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='servingSize',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
