# Generated by Django 4.1.7 on 2023-03-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_number_of_recipes_created'),
        ('shopping_list', '0009_alter_shoppinglistitem_servingsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
