# Generated by Django 4.1.7 on 2023-04-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0021_alter_recipeattachment_attachment'),
        ('shopping_list', '0010_alter_shoppinglistitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='recipeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
    ]
