# Generated by Django 4.1.7 on 2023-03-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id',
            new_name='user',
        ),
    ]
