# Generated by Django 4.1.7 on 2023-03-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_rename_user_id_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
