# Generated by Django 4.1.7 on 2023-03-09 04:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_remove_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
