# Generated by Django 4.1.7 on 2023-03-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_comment_favorite_commentattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='recipe/comment_attachment'),
        ),
        migrations.DeleteModel(
            name='CommentAttachment',
        ),
    ]
