# Generated by Django 4.1.7 on 2023-03-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_alter_comment_options_comment_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='attachment',
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(upload_to='recipe/comment_attachment')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='recipe.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
