# Generated by Django 4.1.7 on 2023-03-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_alter_comment_options_remove_comment_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
