# Generated by Django 4.1.7 on 2023-03-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_alter_comment_user_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='number_of_favorite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
