# Generated by Django 4.1.7 on 2023-03-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_remove_ingredient_unit'),
        ('recipe', '0017_recipe_number_of_favorite'),
    ]

    operations = [
    ]
