# Generated by Django 4.1.7 on 2023-03-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_merge_20230313_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='number_of_favorite',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipe.recipe'),
        ),
    ]
