# Generated by Django 4.1.7 on 2023-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_recipeattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeattachment',
            name='attachment',
            field=models.TextField(),
        ),
    ]
